<a href="https://colab.research.google.com/github/Kishoreram1211/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy - Numerical Python

In [1]:
import numpy as np

List Vs Numpy - Time taken

In [3]:
from time import process_time

Time taken for list

In [7]:
list = [ i for i in range(10000)]
start_time = process_time()
list = [ i+5 for i in list]
end_time = process_time()
end_time - start_time

0.0013116470000005265

Time taken for numpy array

In [8]:
np_array = np.array([ i for i in range(10000)])
start_time = process_time()
np_array += 5
end_time = process_time()
end_time - start_time

0.00017367699999937258

Numpy arrays

In [13]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [15]:
a = np.array([1,2,3,4])
a.shape

(4,)

In [17]:
b = np.array([(1,2,3,4),(5,6,7,8)])
b.shape

(2, 4)

In [19]:
c = np.array([(1,2,3),(4,5,6)],dtype=float)
print(c)

[[1. 2. 3.]
 [4. 5. 6.]]


In [20]:
d = np.zeros((3,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
e = np.full((4,4),5)
print(e)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [24]:
f = np.eye(5)
print(f)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
g = np.random.random((3,4))
print(g)

[[0.14419024 0.19547053 0.32245481 0.90920852]
 [0.34126665 0.20516747 0.00197321 0.34179005]
 [0.70759572 0.20706008 0.64748507 0.49034011]]


In [28]:
h = np.random.randint(1,100,(3,4))
print(h)

[[38 20 89 93]
 [73 29 10 87]
 [48 72 19 61]]


In [30]:
i = np.linspace(10,40,7)
print(i)

[10. 15. 20. 25. 30. 35. 40.]


In [32]:
j = np.arange(10,40,7)
print(j)

[10 17 24 31 38]


In [33]:
#convrting a list to a numpy array
list1 = [ 10,20,30,40,50]
np_array = np.asarray(list1)
print(np_array)

[10 20 30 40 50]


In [34]:
k = np.random.randint(10,100,(5,5))
print(k)

[[79 41 75 87 79]
 [23 74 88 28 18]
 [90 59 51 93 43]
 [25 61 40 72 86]
 [92 64 82 23 33]]


In [38]:
#array dimension
k.shape

(5, 5)

In [39]:
#number of dimensions
k.ndim

2

In [41]:
#number of elements in array
k.size

25

In [42]:
#datatype of elements in array
k.dtype

dtype('int64')

Mathematical operations on numpy array

In [43]:
x = np.random.randint(0,10,(4,4))
y = np.random.randint(10,20,(4,4))

In [45]:
print(x)
print(y)

[[1 6 1 5]
 [5 5 6 5]
 [7 2 0 3]
 [3 4 8 0]]
[[13 10 13 17]
 [11 15 15 13]
 [18 19 11 12]
 [12 11 12 18]]


In [46]:
#addition
print(x+y)

[[14 16 14 22]
 [16 20 21 18]
 [25 21 11 15]
 [15 15 20 18]]


In [49]:
#addition
print(np.add(x,y))

[[14 16 14 22]
 [16 20 21 18]
 [25 21 11 15]
 [15 15 20 18]]


In [50]:
#subtraction
print(x-y)

[[-12  -4 -12 -12]
 [ -6 -10  -9  -8]
 [-11 -17 -11  -9]
 [ -9  -7  -4 -18]]


In [51]:
#subtraction
print(np.subtract(x,y))

[[-12  -4 -12 -12]
 [ -6 -10  -9  -8]
 [-11 -17 -11  -9]
 [ -9  -7  -4 -18]]


In [52]:
#multiplication
print(x*y)

[[ 13  60  13  85]
 [ 55  75  90  65]
 [126  38   0  36]
 [ 36  44  96   0]]


In [53]:
#multiplication
print(np.multiply(x,y))

[[ 13  60  13  85]
 [ 55  75  90  65]
 [126  38   0  36]
 [ 36  44  96   0]]


In [54]:
#division
print(x/y)

[[0.07692308 0.6        0.07692308 0.29411765]
 [0.45454545 0.33333333 0.4        0.38461538]
 [0.38888889 0.10526316 0.         0.25      ]
 [0.25       0.36363636 0.66666667 0.        ]]


In [55]:
#division
print(np.divide(x,y))

[[0.07692308 0.6        0.07692308 0.29411765]
 [0.45454545 0.33333333 0.4        0.38461538]
 [0.38888889 0.10526316 0.         0.25      ]
 [0.25       0.36363636 0.66666667 0.        ]]


Array manipulation

In [56]:
array = np.random.randint(0,10,(2,3))
print(array)
array.shape

[[5 7 1]
 [0 8 1]]


(2, 3)

In [57]:
#transpose
trans = np.transpose(array)
print(trans)
trans.shape

[[5 0]
 [7 8]
 [1 1]]


(3, 2)

In [58]:
#transpose
trans2 = array.T
print(trans2)
trans2.shape

[[5 0]
 [7 8]
 [1 1]]


(3, 2)

In [59]:
#reshaping a array
y = np.random.randint(0,10,(2,3))
print(y)
y.shape

[[3 0 3]
 [2 4 8]]


(2, 3)

In [60]:
z = y.reshape(3,2)
print(z)
z.shape

[[3 0]
 [3 2]
 [4 8]]


(3, 2)